# Generated by Django 3.2.5 on 2024-06-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='locationId',
            new_name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Večerní akce'), (2, 'Workshop'), (3, 'Speciální akce')], default=None),
        ),
    ]
