# Generated by Django 3.2.5 on 2024-06-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_auto_20240614_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lector',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lector',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lector',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
