# Generated by Django 3.2.5 on 2024-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0004_auto_20240614_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
