# Generated by Django 3.2.5 on 2024-06-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0007_lector_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
