# Generated by Django 3.2.5 on 2024-06-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0012_alter_event_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
