# Generated by Django 3.2.5 on 2024-06-12 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('link', models.CharField(max_length=256)),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='DateTime')),
                ('end', models.DateTimeField(default=datetime.datetime.now, verbose_name='DateTime')),
                ('lector', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventLector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.event')),
                ('lectorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.lector')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='locationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.location'),
        ),
        migrations.AddConstraint(
            model_name='eventlector',
            constraint=models.UniqueConstraint(fields=('eventId', 'lectorId'), name='un_eventlector'),
        ),
    ]
