# Generated by Django 3.2.5 on 2024-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0010_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lector',
            field=models.CharField(max_length=50),
        ),
    ]
