# Generated by Django 3.2.5 on 2024-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0016_auto_20240618_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
