# Generated by Django 3.2.5 on 2024-06-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0020_auto_20240621_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.lector'),
        ),
    ]
