# Generated by Django 3.2.5 on 2024-06-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0021_alter_location_lector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='adress',
            new_name='address',
        ),
    ]
