# Generated by Django 3.2.5 on 2024-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0024_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.CharField(max_length=50),
        ),
    ]
