# Generated by Django 3.2.5 on 2024-07-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0025_alter_location_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'ordering': ['firstName']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='lector',
        ),
        migrations.AddField(
            model_name='event',
            name='lector',
            field=models.ManyToManyField(to='danceapp.Lector'),
        ),
    ]
