# Generated by Django 3.2.5 on 2024-07-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0026_auto_20240716_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'ordering': ['firstName']},
        ),
    ]
