# Generated by Django 3.2.5 on 2024-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0027_alter_lector_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lector',
            field=models.ManyToManyField(null=True, to='danceapp.Lector'),
        ),
    ]
