# Generated by Django 3.2.5 on 2024-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0028_alter_event_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lector',
            field=models.ManyToManyField(to='danceapp.Lector'),
        ),
    ]
