# Generated by Django 3.2.5 on 2024-07-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0026_auto_20240718_1559'),
        ('danceapp', '0029_alter_event_lector'),
    ]

    operations = [
    ]
