# Generated by Django 3.2.5 on 2024-07-25 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0030_merge_0026_auto_20240718_1559_0029_alter_event_lector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lector',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, 'Večerní akce'), (2, 'Workshop'), (3, 'Speciální akce')], default=1),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Večerní akce'), (2, 'Workshop'), (3, 'Speciální akce')], default=2)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Začátek')),
                ('end', models.DateTimeField(default=datetime.datetime.now, verbose_name='Konec')),
                ('contact', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('lector', models.ManyToManyField(to='danceapp.Lector')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='18:00')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('lector', models.ManyToManyField(to='danceapp.Lector')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.location')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='danceapp.eventgroup'),
        ),
    ]
