# Generated by Django 3.2.5 on 2024-07-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0031_auto_20240725_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='dates',
        ),
    ]
