# Generated by Django 3.2.5 on 2024-07-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0032_rename_date_event_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dates',
            new_name='date',
        ),
    ]
