# Generated by Django 3.2.5 on 2024-07-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0033_rename_dates_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='type',
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.eventgroup'),
        ),
    ]
