# Generated by Django 3.2.5 on 2024-07-27 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0034_auto_20240727_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatečný popis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.eventgroup', verbose_name='Event Group'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='description',
            field=models.TextField(verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='lector',
            field=models.ManyToManyField(to='danceapp.Lector', verbose_name='Lektor'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.location', verbose_name='Místo konání'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='time',
            field=models.TimeField(default='18:00', verbose_name='Čas'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='lector',
            field=models.ManyToManyField(to='danceapp.Lector', verbose_name='Lektor/Lektoři'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Odkaz (nepovinné)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.location', verbose_name='Místo konání'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cena (nepovinné)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
    ]
