# Generated by Django 3.2.5 on 2024-07-27 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0036_alter_workshop_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Konec'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Začátek'),
        ),
    ]
