# Generated by Django 3.2.5 on 2024-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0037_auto_20240727_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='time',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='endTime',
            field=models.TimeField(blank=True, default='19:00', null=True, verbose_name='Konec (nepovinné)'),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='startTime',
            field=models.TimeField(default='18:00', verbose_name='Začátek'),
        ),
    ]
