# Generated by Django 3.2.5 on 2024-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0038_auto_20240729_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='endTime',
            field=models.TimeField(default='19:00', verbose_name='Konec (nepovinné)'),
        ),
    ]
