# Generated by Django 3.2.5 on 2024-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0039_alter_eventgroup_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='endTime',
            field=models.TimeField(blank=True, default='19:00', null=True, verbose_name='Konec (nepovinné)'),
        ),
    ]
