# Generated by Django 3.2.5 on 2024-07-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0040_alter_eventgroup_endtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Taneční večer', 'verbose_name_plural': 'Taneční večery'},
        ),
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'verbose_name': 'Taneční večer', 'verbose_name_plural': 'Taneční večery'},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'ordering': ['firstName'], 'verbose_name': 'Lektor', 'verbose_name_plural': 'Lektoři'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Místo konání', 'verbose_name_plural': 'Místa konání'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshopy'},
        ),
    ]
