# Generated by Django 3.2.5 on 2024-07-31 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('danceapp', '0041_auto_20240731_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatečný popis (nepovinné)'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='description',
            field=models.TextField(verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Fotka'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Odkaz na stránku'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Adresa (ulice a ČP)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Souřadnice'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Popis (jak se k nám dostat)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danceapp.lector', verbose_name='Lektor'),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(max_length=50, verbose_name='Město/Obec'),
        ),
    ]
