# Generated by Django 3.2.5 on 2024-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0042_auto_20240731_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Fotka'),
        ),
    ]
