# Generated by Django 3.2.5 on 2024-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0043_alter_lector_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Obrázek'),
        ),
    ]
