# Generated by Django 3.2.5 on 2024-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0045_alter_eventgroup_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Název místa (nepovinné)'),
        ),
    ]
