# Generated by Django 3.2.5 on 2024-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0046_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='contact',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Obrázek'),
        ),
    ]
