# Generated by Django 3.2.5 on 2024-11-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0046_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='price',
        ),
        migrations.AddField(
            model_name='workshop',
            name='endTime',
            field=models.TimeField(blank=True, default='20:00', null=True, verbose_name='Konec (nepovinné)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='startTime',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Začátek'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Obrázek'),
        ),
    ]
