# Generated by Django 5.1.2 on 2024-11-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0046_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='endTime',
            field=models.TimeField(blank=True, default='20:00', null=True, verbose_name='Konec (nepovinné)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='startTime',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Začátek (nepovinné)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title2',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Název - 2. řádek (nepovinné)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contact',
            field=models.CharField(default='kontakt', max_length=101),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=101, verbose_name='Název - 1. řádek'),
        ),
    ]
