# Generated by Django 3.2.5 on 2024-11-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0047_auto_20241114_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='startTime',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Obrázek'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cena (nepovinné)'),
        ),
    ]
