# Generated by Django 3.2.5 on 2024-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0047_auto_20240802_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='price',
        ),
        migrations.AddField(
            model_name='workshop',
            name='endTime',
            field=models.TimeField(blank=True, default='20:00', null=True, verbose_name='Konec (nepovinné)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='startTime',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Začátek'),
        ),
    ]
