# Generated by Django 3.2.5 on 2024-11-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0048_auto_20241114_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='endTime',
            field=models.TimeField(blank=True, default='20:00', null=True, verbose_name='Konec (nepovinné)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='startTime',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Začátek'),
        ),
    ]
