# Generated by Django 3.2.5 on 2024-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0048_auto_20241118_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Fotka'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='lector',
        ),
        migrations.AddField(
            model_name='location',
            name='lector',
            field=models.ManyToManyField(to='danceapp.Lector', verbose_name='Lektor'),
        ),
    ]
