# Generated by Django 3.2.5 on 2024-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0049_auto_20241116_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='startTime',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Začátek (nepovinné)'),
        ),
    ]
