# Generated by Django 3.2.5 on 2024-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0049_auto_20241124_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='endTime',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Konec (nepovinné)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='startTime',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Začátek (nepovinné)'),
        ),
    ]
