# Generated by Django 3.2.5 on 2024-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0050_auto_20241116_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='title',
        ),
        migrations.AddField(
            model_name='workshop',
            name='title1',
            field=models.CharField(default='nazev', max_length=101, verbose_name='Název - 1. řádek'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title2',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Název = ě. řádek (nepovinné)'),
        ),
    ]
