# Generated by Django 3.2.5 on 2024-11-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0050_auto_20241124_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis (nepovinné)'),
        ),
    ]
