# Generated by Django 3.2.5 on 2024-11-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0052_auto_20241116_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=101, verbose_name='Název - 1. řádek'),
        ),
    ]
