# Generated by Django 3.2.5 on 2025-01-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0052_auto_20241208_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlector',
            options={'ordering': ['order'], 'verbose_name': 'Lektor', 'verbose_name_plural': 'Lektoři'},
        ),
        migrations.AddField(
            model_name='eventlector',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='eventlector',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.eventgroup'),
        ),
    ]
