# Generated by Django 3.2.5 on 2025-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0054_rename_lector_eventgroup_lectorold'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='lector',
            field=models.ManyToManyField(through='danceapp.EventLector', to='danceapp.Lector', verbose_name='Lektor'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='lectorOld',
            field=models.ManyToManyField(related_name='event_groups_old', to='danceapp.Lector', verbose_name='LektorOld'),
        ),
    ]
