# Generated by Django 3.2.5 on 2025-01-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0055_auto_20250116_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='lectorOld',
        ),
    ]
