# Generated by Django 3.2.5 on 2025-01-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0056_remove_eventgroup_lectorold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lektor', 'verbose_name_plural': 'Lektoři'},
        ),
        migrations.AddField(
            model_name='eventlector',
            name='workshopId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='danceapp.workshop'),
        ),
        migrations.AlterField(
            model_name='eventlector',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Pořadí'),
        ),
        migrations.AddConstraint(
            model_name='eventlector',
            constraint=models.UniqueConstraint(fields=('workshopId', 'lectorId'), name='un_workshoplector'),
        ),
    ]
