# Generated by Django 3.2.5 on 2025-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0058_rename_lector_workshop_lectorold'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='lector',
            field=models.ManyToManyField(related_name='workshops', through='danceapp.EventLector', to='danceapp.Lector', verbose_name='Lektor'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='lectorOld',
            field=models.ManyToManyField(related_name='workshops_old', to='danceapp.Lector', verbose_name='Lektor/Lektoři'),
        ),
    ]
