# Generated by Django 3.2.5 on 2025-01-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0059_auto_20250116_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlector',
            name='eventId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='danceapp.eventgroup'),
        ),
    ]
