# Generated by Django 3.2.5 on 2025-01-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0060_alter_eventlector_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='lectorOld',
        ),
    ]
