# Generated by Django 3.2.5 on 2025-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0061_remove_workshop_lectorold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='lector',
            field=models.ManyToManyField(through='danceapp.EventLector', to='danceapp.Lector', verbose_name='Lektor'),
        ),
    ]
