# Generated by Django 3.2.5 on 2025-09-09 15:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0062_alter_workshop_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(default='CZ', max_length=2, verbose_name='Země'),
        ),
    ]
