# Generated by Django 3.2.5 on 2025-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0064_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('CZ', 'Česko'), ('DE', 'Německo'), ('SK', 'Slovensko'), ('AT', 'Rakousko'), ('PL', 'Polsko'), ('NL', 'Nizozemsko'), ('UK', 'Velká Británie'), ('FR', 'Francie')], default='CZ', max_length=2),
        ),
    ]
