# Generated by Django 3.2.5 on 2024-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0006_rename_address_event_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
