# Generated by Django 5.0.6 on 2024-06-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('town', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lector', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
