# Generated by Django 5.0.6 on 2024-06-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
