# Generated by Django 3.2.5 on 2024-06-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0002_remove_events_date_remove_events_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
