# Generated by Django 3.2.5 on 2024-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0005_auto_20240604_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='adress',
        ),
    ]
