# .github/workflows/rosti_deploy.yml

name: Deploy into Roští.cz

on:
  workflow_dispatch:
  push:
    branches:
      - rosti

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        HOST: ssh.rosti.cz
        USER: app
        PORT: 14817
        PYTHON_VERSION: 3.12.3
      steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ROSTI_DEPLOY_SSH_KEY }}
      - name: Setup hostkey
        run: |
          echo "ssh.rosti.cz ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCBQLdOpCnDXFL/e6SexPmJEHPfsl9E0rcfBTqAuFgaTySjGBrHSgLezg1LQDlmxPVOXmqS2zCbX7UjnNpkGwW5m5kQwZTKpBF2iabrDTq/hX2GtzBfLLZNJbiQZ1QSxosgr/9makFEsu8Cnl8mBZx3WypJAPZD4taAm6gCWIZBYhrfN1DNHlockU8GLwfINnY8hgLZSntePjujKAyihUAryUd+dw9LXlzEZGB747yHCJ22HCXs8IxaizLJyX2f/eyGDjpeAlR1O7jRbY9P1RzIbOojT4XAgUqB7WXyGLJY8GF8KKLFLets4TMugdfyvvsEIS7oTNr6EZOwvna+1dih" > ./known_hosts
      - name: Env
        run: |
          cat << EOF > .env
          ${{ secrets.ENV }}
          EOF
      - name: Setup Python
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST /usr/local/bin/rosti python $PYTHON_VERSION
      - name: Setup Nginx
        run: |
          cat << EOF > rosti.nginx.conf
          server {
              listen       0.0.0.0:8000;
              listen       [::]:8000;
              location / {
                      proxy_pass         http://127.0.0.1:8080/;
                      proxy_redirect     default;
                      proxy_set_header   X-Real-IP  \$remote_addr;
                      proxy_set_header   Host       \$host;
              }
              location /static/ {
                      alias /srv/app/static/;
              }
              location /static/admin/ {
                      alias /srv/app/static/;
              }
          }        
          EOF
          scp -o UserKnownHostsFile=./known_hosts -P $PORT rosti.nginx.conf $USER@$HOST:/srv/conf/nginx.d/app.conf
          rm rosti.nginx.conf
      - name: Backup SQLite Database
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST "cp /srv/app/db.sqlite3 /srv/app/db_backup_\$TIMESTAMP.sqlite3"
      - name: Copy code
        run: |
          rsync -ae "ssh -o UserKnownHostsFile=./known_hosts -p $PORT" --delete-after --exclude=.git --exclude=db.sqlite3 ./web/dance_web/ $USER@$HOST:/srv/app/
      - name: install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Apply changes
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl reread
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart app
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart nginx
